awslabs/amazon-kinesis-agent

src/com/amazon/kinesis/streaming/agent/processing/parsers/PatternConstants.java, src/com/amazon/kinesis/streaming/agent/processing/parsers/SysLogParser.java, src/com/amazon/kinesis/streaming/agent/processing/utils/ProcessingUtilsFactory.java
Adds a new logformat option for syslog entries with RFC3339 timestamps.
I've removed unnecessary whitespace which makes things look a bit messy :-(
Also I tested locally but I'm not sure how to use your test suite.
=> RFC3339 timestamps

.gitignore, README.md, bin/aws-kinesis-agent.RedHat, bin/aws-kinesis-agent.Ubuntu, build.xml, setup, support/aws-kinesis-agent.sysconfig
This commit refactors the setup script so that its a little more
idempotent, easier to read the output of the wget downloads, and now
supports Ubuntu as well as RHEL/AmazonLinux.
We also create a new Ubuntu-specific startup script thats vastly simpler
than the RedHat/Amazon Linux script.
@rayzhu19, this is a WIP ... It functions on my local dev box, but we havn't done any production-style deploys yet with it. What are your thoughts on the initial work though?
=> Initial support for installing the agent on Ubuntu hosts.

setup
group_id gets assigned but not used.  Used it in place of positional $1.
=> Fixes an oversight in setup

bin/aws-kinesis-agent.RedHat
Running `mkdir -p` resulted in the `/var/run/aws-kinesis-agent`
directory being created as root, but the aws-kinesis-agent-user user
needs to have permissions to that directory. This change results in
`aws-kinesis-agent-user` being the owner of the directory, instead of
root.
=> fix permissions issue in RedHat startup script

pom.xml, setup, src/com/amazon/kinesis/streaming/agent/AgentAWSCredentialsProviderChain.java
Add support to IAM Roles for Tasks including ContainerCredentialsProvider.
Also update aws-sdk to latest version (1.11.28) to have it working.
=> Add support to IAM Roles for Tasks & update aws-sdk to version 1.11.28

bin/aws-kinesis-agent-babysit, bin/aws-kinesis-agent.RedHat
Fixes #47 
- Wraps all commands inside a mutex region.
- Closes file descriptor (200) so as not to be inherited by the daemon.
- Pushes babysit status check into sysvinit script so it can benefit
from being inside a mutex region for atomic execution.
=> Fix for race condition from babysit cron job

src/com/amazon/kinesis/streaming/agent/processing/processors/AddMetadataConverter.java, src/com/amazon/kinesis/streaming/agent/processing/utils/ProcessingUtilsFactory.java
This will allow for the addition of metadata in JSON format via configuration in each flow:
```json 
"flows": [
{
"filePattern": "/tmp/aws-kinesis-agent-test1.log*",
"initialPosition": "END_OF_FILE",
"kinesisStream": "aws-kinesis-agent-test1",
"dataProcessingOptions": [
{
"optionName": "ADDMETADATA",
"metadata": {
"key": "value",
"foo": {
"bar": "baz"
}
}
}
]
}
]
```
The above configuration would result in a record format that looks like this:
`{"metadata":{"key":"value","foo":{"bar":"baz"}},"data":"this is my raw data that I want to send"}`
or formatted:
```json
{
"metadata": {
"key": "value",
"foo": {
"bar": "baz"
}
},
"data": "this is my raw data that I want to send"
}
```
=> ADDMETADATA feature to allow addition of arbitrary metadata in JSON format

pom.xml, setup, src/com/amazon/kinesis/streaming/agent/processing/processors/AddEC2MetadataConverter.java, src/com/amazon/kinesis/streaming/agent/processing/utils/ProcessingUtilsFactory.java
EC2 metadata processor retrieves metadata from the EC2 instance metadata service and retrieves the instance tags via a EC2 describe tags request. The metadata is then merged with the json data. 
The metadata is requested on startup and updated on the next log request when the metadataTimestamp + metadataTTL is in the past, metadataTTL default is 60 minutes.
Security - The instance role needs to have EC2 describe tags IAM permissions.
The following data is merged to all the log entries:
- privateIp
- availabilityZone
- instanceId
- instanceType
- accountId
- amiId (imageId)
- region
- metadataTimestamp (iso timestamp of metadata update)
Sample usage:
```
"flows": [{
"filePattern": "/var/log/syslog",
"deliveryStream": "your-system-log-stream",
"dataProcessingOptions": [{
"optionName": …
```
=> EC2 metadata processor

setup, src/com/amazon/kinesis/streaming/agent/Agent.java
The agent config directory for flow configurations allows configuration management systems to add additional flows dynamically without having to edit the main configuration in place.
Similar to other linux services, this change creates a .d at /etc/aws-kinesis/agent.d/ where additional flow configurations can be added in multiple files. The agent will read the main configuration file and then append the multiple flow configurations in /etc/aws-kinesis/agent.d/.
The flow configurations have the exact same structure as the main agent configuration, but only the flow items will be appended to the final configuration, everything else is ignored.
Below an example of a flow configuration for MongoDB:
/etc/aws-kinesis/agent.d/mongodb_log.json
```
{
"flows": [
{
"filePattern": …
```
=> Agent config directory for flow configurations

setup
On some systems (e.g. ubuntu 14.04 docker) wget isn't installed by default.
=> Installs wget dependency

build.xml
Most systems already have Java installed, in our case OracleJDK which is a custom path. Because of this, the install of this will fail. This PR is to change hard coded path for java to use the current java home that is running ant. As long as java is in the PATH, this should work assuming its a JDK.
=> Update hardcoded JAVA_HOME path in the build.xml

src/com/amazon/kinesis/streaming/agent/tailing/AbstractParser.java, src/com/amazon/kinesis/streaming/agent/tailing/FileFlow.java
There is no need to for the noop regex if the pattern is null or empty since there is a null check in place
=> Remove redundant file footer pattern noop regex

src/com/amazon/kinesis/streaming/agent/processing/processors/SingleLineDataConverter.java, src/com/amazon/kinesis/streaming/agent/processing/utils/ProcessingUtilsFactory.java
This is a solution for [YAML log(dnstap)](https://gist.github.com/edmonds/5772879#file-dnstap-yaml).
New option "parseOptions"(not required) is added to "SINGLELINE". 
This option provides 2 features.
- NO_TRIM: stop each line trim.
- ESCAPE_NEW_LINE: escape new line "\\\\n" (like json)
Configuration sample
```
"dataProcessingOptions": [
{
"optionName": "SINGLELINE",
"parseOptions": ["ESCAPE_NEW_LINE"]
}
]
```
=> add notrim,escape_new_line to singleline mode

src/com/amazon/kinesis/streaming/agent/processing/processors/PluggableDataConverter.java, src/com/amazon/kinesis/streaming/agent/processing/utils/ProcessingUtilsFactory.java
This PR provides the support for a new data conversion option, `USINGPLUGGIN`,  which will load an external java class to delegate the actual task of converting the bytes.
This will enable to easily plug external classes without requiring to modify the amazon source code.
The bare minimum to configure this converted is:
```json
{
"optionName": "USINGPLUGGIN",
"className": "org.example.MyDataConverter"
}
```
Optionally the `PluggableDataConverter` exposes such configuration when the external class contains a constructor with a single configuration parameter. 
```java
package org.example;
class MyExampleConverter implements IDataConverter {
public MyExampleConverter (Configuration config) {
// use config.readString() as usually
}
}
```
Finally, please let me know your thoughts and if you …
=> Pluggable data converter

build.xml
Please see the below stack trace. Code compiled with ant does not show line numbers.
```
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
at [Source: [B@578469d; line: 1, column: 1]
at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3781)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2294)
at com.amazonaws.http.JsonErrorResponseHandler$JsonContent.parseJsonContent(JsonErrorResponseHandler.java:178)
at com.amazonaws.http.JsonErrorResponseHandler$JsonContent.<init>(JsonErrorResponseHandler.java:169)
at …
```
=> Fixes unknown source problem in exception stacktraces.

.travis.yml
*Description of changes:* specify openjdk8 so travis-ci doesn't default to the unsupported java 11.
=> travis-ci explicitly use openjdk8

src/com/amazon/kinesis/streaming/agent/AgentContext.java, src/com/amazon/kinesis/streaming/agent/config/AgentConfiguration.java
*Issue #, if available:* #207 
This change adds a new configuration value named `kinesis.region` which allows the user to explicitly configure the region that kinesis should use. As explained in #207, `AWS_DEFAULT_REGION` is not sufficient as it gets overridden by some magic in the aws client that parses what it thinks is a region from the endpoint url.
=> add kinesis.region config option

src/com/amazon/kinesis/streaming/agent/providers/CLIWebIdentityTokenCredentialsProvider.java
Make the credentials provider always retrieve the Web Identity token on credential refresh, since it can get rotated by the system underneath.
=> Bug fix in CLIWebIdentityProvider

configuration/example/agent.json
The UserDefinedCredentialsProvided looks for userDefinedCredentialsProvider.classname (lowercase classname) but the provided sample configuration uses mixed case. This commit fixes the example to match what the provider expects https://github.com/awslabs/amazon-kinesis-agent/blob/master/src/com/amazon/kinesis/streaming/agent/UserDefinedCredentialsProvider.java#L23
=> Fix sample agent.json to use correct userDefinedCredentialsProvider.classname key

src/com/amazon/kinesis/streaming/agent/AgentAWSCredentialsProviderChain.java
Add WebIdentityTokenCredentialsProvider to the Agent chain. This is needed for [IRSA roles](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html) to work and is already included in the DefaultAWSCredentialsProviderChain in the AWS SDK https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.java#L60
=> Add WebIdentityTokenCredentialsProvider to the Agent chain

build.xml, pom.xml, setup
Upgrading Jackson-databind dependency to 2.17.x.
=> upgrade jackson databind dependency

src/com/amazon/kinesis/streaming/agent/AgentContext.java, tst/com/amazon/kinesis/streaming/agent/tailing/KinesisSenderTest.java
#194 
When setting the region and endpoint in the config with values `kinesis.endpoint` and `kinesis.region`, the region would override the endpoint. The correct way of setting both a region and endpoint is described in https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html with `EndpointConfiguration`. This change also ensures that users who were using this functioanlity by only supplying `kinesis.endpoint` will have the same backwards compatible behavior with this commit, even though the behavior may be erroneous. 
=> Bugfix for setting kinesis.region and kinesis.endpoint in config

src/com/amazon/kinesis/streaming/agent/tailing/KinesisSender.java
Move initialization of the kinesis client to send constructor instead of doing this on the data plane path
=> Move Kinesis client construction to sender constructor
